name: wallet

volumes:
  pgdata:

networks:
  wallet-network:
    driver: bridge

services:
  app:
    build:
      context: ..
      dockerfile: deployments/DockerfileApp
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ../:/app:rw
    env_file:
      - ../configs/.env
    networks:
      - wallet-network

  postgres:
    image: postgres:17-alpine
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: wallet_user
      POSTGRES_PASSWORD: wallet_pass
      POSTGRES_DB: wallet
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U wallet_user -d wallet" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - wallet-network

